// Copyright 2026, Command Line Inc.
// SPDX-License-Identifier: Apache-2.0

// generated by cmd/generate/main-generatets.go

declare global {

    // wps.WaveEvent
    type WaveEventName =
        | "blockclose"
        | "connchange"
        | "sysinfo"
        | "controllerstatus"
        | "builderstatus"
        | "builderoutput"
        | "waveobj:update"
        | "blockfile"
        | "config"
        | "userinput"
        | "route:down"
        | "route:up"
        | "workspace:update"
        | "waveai:ratelimit"
        | "waveapp:appgoupdated"
        | "tsunami:updatemeta"
        | "termlisten:down"
        | "waveai:modeconfig"
        | "block:jobstatus"
        | "badge"
    ;

    type WaveEvent = {
        event: WaveEventName;
        scopes?: string[];
        sender?: string;
        persist?: number;
        data?: unknown;
    } & (
        { event: "blockclose"; data?: string; } | 
        { event: "connchange"; data?: ConnStatus; } | 
        { event: "sysinfo"; data?: TimeSeriesData; } | 
        { event: "controllerstatus"; data?: BlockControllerRuntimeStatus; } | 
        { event: "builderstatus"; data?: BuilderStatusData; } | 
        { event: "builderoutput"; data?: {[key: string]: any}; } | 
        { event: "waveobj:update"; data?: WaveObjUpdate; } | 
        { event: "blockfile"; data?: WSFileEventData; } | 
        { event: "config"; data?: WatcherUpdate; } | 
        { event: "userinput"; data?: UserInputRequest; } | 
        { event: "route:down"; data?: null; } | 
        { event: "route:up"; data?: null; } | 
        { event: "workspace:update"; data?: null; } | 
        { event: "waveai:ratelimit"; data?: RateLimitInfo; } | 
        { event: "waveapp:appgoupdated"; data?: null; } | 
        { event: "tsunami:updatemeta"; data?: AppMeta; } | 
        { event: "termlisten:down"; data?: TermListenDownData; } | 
        { event: "waveai:modeconfig"; data?: AIModeConfigUpdate; } | 
        { event: "block:jobstatus"; data?: BlockJobStatusData; } | 
        { event: "badge"; data?: BadgeEvent; }
    );

}

export {}
