// Copyright 2025, Command Line Inc.
// SPDX-License-Identifier: Apache-2.0

// generated by cmd/generate/main-generatets.go

declare global {

    // wps.WaveEvent
    type WaveEventName = "blockclose" | "connchange" | "sysinfo" | "controllerstatus" | "builderstatus" | "builderoutput" | "waveobj:update" | "blockfile" | "config" | "userinput" | "route:down" | "route:up" | "workspace:update" | "waveai:ratelimit" | "waveapp:appgoupdated" | "tsunami:updatemeta" | "waveai:modeconfig" | "tab:indicator" | "block:jobstatus";

    type WaveEvent = {
        event: WaveEventName;
        scopes?: string[];
        sender?: string;
        persist?: number;
        data?: any;
    } & (
        { event: "blockclose"; data?: string; } | 
        { event: "connchange"; data?: ConnStatus; } | 
        { event: "sysinfo"; data?: TimeSeriesData; } | 
        { event: "controllerstatus"; data?: BlockControllerRuntimeStatus; } | 
        { event: "builderstatus"; data?: BuilderStatusData; } | 
        { event: "builderoutput"; data?: {[key: string]: any}; } | 
        { event: "waveobj:update"; data?: WaveObjUpdate; } | 
        { event: "blockfile"; data?: WSFileEventData; } | 
        { event: "config"; data?: WatcherUpdate; } | 
        { event: "userinput"; data?: UserInputRequest; } | 
        { event: "route:down"; data?: any; } | 
        { event: "route:up"; data?: any; } | 
        { event: "workspace:update"; data?: any; } | 
        { event: "waveai:ratelimit"; data?: RateLimitInfo; } | 
        { event: "waveapp:appgoupdated"; data?: any; } | 
        { event: "tsunami:updatemeta"; data?: AppMeta; } | 
        { event: "waveai:modeconfig"; data?: AIModeConfigUpdate; } | 
        { event: "tab:indicator"; data?: TabIndicatorEventData; } | 
        { event: "block:jobstatus"; data?: BlockJobStatusData; }
    );

}

export {}
