// Copyright 2026, Command Line Inc.
// SPDX-License-Identifier: Apache-2.0

// generated by cmd/generate/main-generatets.go

import * as WOS from "./wos";
import type { WaveEnv } from "@/app/waveenv/waveenv";

function callBackendService(waveEnv: WaveEnv, service: string, method: string, args: any[], noUIContext?: boolean): Promise<any> {
    if (waveEnv != null) {
        return waveEnv.callBackendService(service, method, args, noUIContext)
    }
    return WOS.callBackendService(service, method, args, noUIContext);
}

// blockservice.BlockService (block)
export class BlockServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    // queue a layout action to cleanup orphaned blocks in the tab
    // @returns object updates
    CleanupOrphanedBlocks(tabId: string): Promise<void> {
        return callBackendService(this?.waveEnv, "block", "CleanupOrphanedBlocks", Array.from(arguments))
    }
    GetControllerStatus(arg2: string): Promise<BlockControllerRuntimeStatus> {
        return callBackendService(this?.waveEnv, "block", "GetControllerStatus", Array.from(arguments))
    }

    // save the terminal state to a blockfile
    SaveTerminalState(blockId: string, state: string, stateType: string, ptyOffset: number, termSize: TermSize): Promise<void> {
        return callBackendService(this?.waveEnv, "block", "SaveTerminalState", Array.from(arguments))
    }
    SaveWaveAiData(arg2: string, arg3: WaveAIPromptMessageType[]): Promise<void> {
        return callBackendService(this?.waveEnv, "block", "SaveWaveAiData", Array.from(arguments))
    }
}

export const BlockService = new BlockServiceType();

// clientservice.ClientService (client)
export class ClientServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    // @returns object updates
    AgreeTos(): Promise<void> {
        return callBackendService(this?.waveEnv, "client", "AgreeTos", Array.from(arguments))
    }
    FocusWindow(arg2: string): Promise<void> {
        return callBackendService(this?.waveEnv, "client", "FocusWindow", Array.from(arguments))
    }
    GetAllConnStatus(): Promise<ConnStatus[]> {
        return callBackendService(this?.waveEnv, "client", "GetAllConnStatus", Array.from(arguments))
    }
    GetClientData(): Promise<Client> {
        return callBackendService(this?.waveEnv, "client", "GetClientData", Array.from(arguments))
    }
    GetTab(arg1: string): Promise<Tab> {
        return callBackendService(this?.waveEnv, "client", "GetTab", Array.from(arguments))
    }
    TelemetryUpdate(arg2: boolean): Promise<void> {
        return callBackendService(this?.waveEnv, "client", "TelemetryUpdate", Array.from(arguments))
    }
}

export const ClientService = new ClientServiceType();

// messageservice.MessageService (message)
export class MessageServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    // get all messages for an agent session
    GetMessages(sessionId: string): Promise<Message[]> {
        return callBackendService(this?.waveEnv, "message", "GetMessages", Array.from(arguments))
    }

    // send a message to an agent session with streaming events
    SendMessage(input: SendMessageInput): Promise<string> {
        return callBackendService(this?.waveEnv, "message", "SendMessage", Array.from(arguments))
    }
    SendMessageWithStream(arg2: any, arg3: SendMessageInput): Promise<any> {
        return callBackendService(this?.waveEnv, "message", "SendMessageWithStream", Array.from(arguments))
    }
    SetStore(arg1: any): Promise<void> {
        return callBackendService(this?.waveEnv, "message", "SetStore", Array.from(arguments))
    }
}

export const MessageService = new MessageServiceType();

// objectservice.ObjectService (object)
export class ObjectServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    // @returns blockId (and object updates)
    CreateBlock(blockDef: BlockDef, rtOpts: RuntimeOpts): Promise<string> {
        return callBackendService(this?.waveEnv, "object", "CreateBlock", Array.from(arguments))
    }

    // @returns object updates
    DeleteBlock(blockId: string): Promise<void> {
        return callBackendService(this?.waveEnv, "object", "DeleteBlock", Array.from(arguments))
    }

    // get wave object by oref
    GetObject(oref: string): Promise<WaveObj> {
        return callBackendService(this?.waveEnv, "object", "GetObject", Array.from(arguments))
    }

    // @returns objects
    GetObjects(orefs: string[]): Promise<WaveObj[]> {
        return callBackendService(this?.waveEnv, "object", "GetObjects", Array.from(arguments))
    }

    // @returns object updates
    UpdateObject(waveObj: WaveObj, returnUpdates: boolean): Promise<void> {
        return callBackendService(this?.waveEnv, "object", "UpdateObject", Array.from(arguments))
    }

    // @returns object updates
    UpdateObjectMeta(oref: string, meta: MetaType): Promise<void> {
        return callBackendService(this?.waveEnv, "object", "UpdateObjectMeta", Array.from(arguments))
    }
}

export const ObjectService = new ObjectServiceType();

// userinputservice.UserInputService (userinput)
export class UserInputServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    SendUserInputResponse(arg1: UserInputResponse): Promise<void> {
        return callBackendService(this?.waveEnv, "userinput", "SendUserInputResponse", Array.from(arguments))
    }
}

export const UserInputService = new UserInputServiceType();

// windowservice.WindowService (window)
export class WindowServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    CloseWindow(windowId: string, fromElectron: boolean): Promise<void> {
        return callBackendService(this?.waveEnv, "window", "CloseWindow", Array.from(arguments))
    }
    CreateWindow(winSize: WinSize, workspaceId: string): Promise<WaveWindow> {
        return callBackendService(this?.waveEnv, "window", "CreateWindow", Array.from(arguments))
    }
    GetWindow(windowId: string): Promise<WaveWindow> {
        return callBackendService(this?.waveEnv, "window", "GetWindow", Array.from(arguments))
    }

    // set window position and size
    // @returns object updates
    SetWindowPosAndSize(windowId: string, pos: Point, size: WinSize): Promise<void> {
        return callBackendService(this?.waveEnv, "window", "SetWindowPosAndSize", Array.from(arguments))
    }
    SwitchWorkspace(windowId: string, workspaceId: string): Promise<Workspace> {
        return callBackendService(this?.waveEnv, "window", "SwitchWorkspace", Array.from(arguments))
    }
}

export const WindowService = new WindowServiceType();

// workspaceservice.WorkspaceService (workspace)
export class WorkspaceServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    // @returns CloseTabRtn (and object updates)
    CloseTab(workspaceId: string, tabId: string, fromElectron: boolean): Promise<CloseTabRtnType> {
        return callBackendService(this?.waveEnv, "workspace", "CloseTab", Array.from(arguments))
    }

    // @returns tabId (and object updates)
    CreateTab(workspaceId: string, tabName: string, activateTab: boolean): Promise<string> {
        return callBackendService(this?.waveEnv, "workspace", "CreateTab", Array.from(arguments))
    }

    // @returns workspaceId
    CreateWorkspace(name: string, icon: string, color: string, applyDefaults: boolean): Promise<string> {
        return callBackendService(this?.waveEnv, "workspace", "CreateWorkspace", Array.from(arguments))
    }

    // @returns object updates
    DeleteWorkspace(workspaceId: string): Promise<string> {
        return callBackendService(this?.waveEnv, "workspace", "DeleteWorkspace", Array.from(arguments))
    }

    // @returns colors
    GetColors(): Promise<string[]> {
        return callBackendService(this?.waveEnv, "workspace", "GetColors", Array.from(arguments))
    }

    // @returns icons
    GetIcons(): Promise<string[]> {
        return callBackendService(this?.waveEnv, "workspace", "GetIcons", Array.from(arguments))
    }

    // @returns workspace
    GetWorkspace(workspaceId: string): Promise<Workspace> {
        return callBackendService(this?.waveEnv, "workspace", "GetWorkspace", Array.from(arguments))
    }
    ListWorkspaces(): Promise<WorkspaceListEntry[]> {
        return callBackendService(this?.waveEnv, "workspace", "ListWorkspaces", Array.from(arguments))
    }

    // @returns object updates
    SetActiveTab(workspaceId: string, tabId: string): Promise<void> {
        return callBackendService(this?.waveEnv, "workspace", "SetActiveTab", Array.from(arguments))
    }

    // @returns object updates
    UpdateWorkspace(workspaceId: string, name: string, icon: string, color: string, applyDefaults: boolean): Promise<void> {
        return callBackendService(this?.waveEnv, "workspace", "UpdateWorkspace", Array.from(arguments))
    }
}

export const WorkspaceService = new WorkspaceServiceType();

// zeroaiservice.ZeroaiService (zeroai)
export class ZeroaiServiceType {
    waveEnv: WaveEnv;

    constructor(waveEnv?: WaveEnv) {
        this.waveEnv = waveEnv;
    }

    // @returns AgentSession
    CreateSession(workDir: AgentSessionOptions): Promise<AgentSession> {
        return callBackendService(this?.waveEnv, "zeroai", "CreateSession", Array.from(arguments))
    }

    // @returns object updates
    DeleteSession(sessionId: string): Promise<void> {
        return callBackendService(this?.waveEnv, "zeroai", "DeleteSession", Array.from(arguments))
    }

    // @returns AgentSession
    GetSession(sessionId: string): Promise<AgentSession> {
        return callBackendService(this?.waveEnv, "zeroai", "GetSession", Array.from(arguments))
    }
    Initialize(arg1: any, arg2: any): Promise<void> {
        return callBackendService(this?.waveEnv, "zeroai", "Initialize", Array.from(arguments))
    }

    // @returns []AgentSession
    ListSessions(): Promise<AgentSession[]> {
        return callBackendService(this?.waveEnv, "zeroai", "ListSessions", Array.from(arguments))
    }

    // @returns object updates
    SetWorkDir(sessionId: string, workDir: string): Promise<void> {
        return callBackendService(this?.waveEnv, "zeroai", "SetWorkDir", Array.from(arguments))
    }
}

export const ZeroaiService = new ZeroaiServiceType();

export const AllServiceTypes = {
    "block": BlockServiceType,
    "client": ClientServiceType,
    "message": MessageServiceType,
    "object": ObjectServiceType,
    "userinput": UserInputServiceType,
    "window": WindowServiceType,
    "workspace": WorkspaceServiceType,
    "zeroai": ZeroaiServiceType,
};

export const AllServiceImpls = {
    "block": BlockService,
    "client": ClientService,
    "message": MessageService,
    "object": ObjectService,
    "userinput": UserInputService,
    "window": WindowService,
    "workspace": WorkspaceService,
    "zeroai": ZeroaiService,
};
