name: ðŸž Bug Report
description: Create a bug report to help us improve.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
    - type: markdown
      attributes:
          value: |
              ## Bug description
    - type: textarea
      attributes:
          label: Current Behavior
          description: A concise description of what you're experiencing.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Expected Behavior
          description: A concise description of what you expected to happen.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Steps To Reproduce
          description: Steps to reproduce the behavior.
          placeholder: |
              1. In this environment...
              2. With this config...
              3. Run '...'
              4. See error...
      validations:
          required: true

    - type: markdown
      attributes:
          value: |
              ## Environment details

              We require that you provide us the version of Wave you're running so we can track issues across versions. To find the Wave version, go to the app menu (this always visible on macOS, for Windows and Linux, click the `...` button) and navigate to `Wave -> About Wave Terminal`. This will bring up the About modal. Copy the client version and paste it below.
    - type: input
      attributes:
          label: Wave Version
          description: The version of Wave you are running
          placeholder: v0.8.8
      validations:
          required: true
    - type: dropdown
      attributes:
          label: Platform
          description: The OS platform of the computer where you are running Wave
          options:
              - macOS
              - Linux
              - Windows
      validations:
          required: true
    - type: input
      attributes:
          label: OS Version/Distribution
          description: The version of the operating system of the computer where you are running Wave
          placeholder: Ubuntu 24.04
      validations:
          required: false
    - type: dropdown
      attributes:
          label: Architecture
          description: The architecture of the computer where you are running Wave
          options:
              - arm64
              - x64
      validations:
          required: true

    - type: markdown
      attributes:
          value: |
              ## Extra details
    - type: textarea
      attributes:
          label: Anything else?
          description: |
              Links? References? Anything that will give us more context about the issue you are encountering!

              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      validations:
          required: false
