name: 🚀 Feature Request / Idea
description: Suggest a new idea for this project.
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
    - type: textarea
      attributes:
          label: Feature description
          description: Describe the issue in detail and why we should add it. To help us out, please poke through our issue tracker and make sure it's not a duplicate issue. Ex. As a user, I can do [...]
      validations:
          required: true
    - type: textarea
      attributes:
          label: Implementation Suggestion
          description: If you have any suggestions on how to design this feature, list them here.
      validations:
          required: false
    - type: textarea
      attributes:
          label: Anything else?
          description: |
              Links? References? Anything that will give us more context about how to deliver your feature!

              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      validations:
          required: false
